from sqlalchemy import Column, Integer, String, JSON, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func
from pgvector.sqlalchemy import Vector

Base = declarative_base()

class MediaAsset(Base):
    __tablename__ = "media_assets"

    id = Column(Integer, primary_key=True)
    designer_id = Column(Integer, index=True)
    original_filename = Column(String)
    s3_key = Column(String) # Path to raw file
    optimized_key = Column(String) # Path to web-ready file
    status = Column(String, default="processing") # pending, processing, ready, error
    
    # Metadata generated by AI
    ai_tags = Column(JSON) # e.g., ["branding", "logo", "vector"]
    color_palette = Column(JSON) # e.g., ["#FFFFFF", "#000000"]
    
    # Vector embedding for Semantic Matching (RAG)
    # Using 1536 dims for OpenAI or 768 for HuggingFace models
    embedding = Column(Vector(1536)) 
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())